project_id = "know-wedding"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public", "nowedding"]
extra_search_path = ["public", "extensions", "nowedding"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[functions.payment_webhook]
verify_jwt = false
